-- Every table of a RAWmakase catalog on a PostgreSQL server: the same tables
-- and columns as schema.sql (SQLite), with identity ids, BIGINT integers and
-- byte-order ("C") text, so photos sort as they do in a local catalog.
-- Idempotent, like schema.sql; keep the two in step.
--
-- Rows whose ids come from a Lightroom import or a local catalog keep them;
-- `Catalog::import_into` moves each identity sequence past the largest.

CREATE TABLE IF NOT EXISTS sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path TEXT COLLATE "C" NOT NULL,
    imported_at TEXT COLLATE "C" NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    original_size BIGINT NOT NULL,
    original_catalog BYTEA NOT NULL
);

CREATE TABLE IF NOT EXISTS roots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_path TEXT COLLATE "C" NOT NULL,
    mapped_path TEXT COLLATE "C"
);

CREATE TABLE IF NOT EXISTS folders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    root BIGINT NOT NULL REFERENCES roots(id),
    relative_path TEXT COLLATE "C" NOT NULL
);

CREATE TABLE IF NOT EXISTS photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder BIGINT NOT NULL REFERENCES folders(id),
    filename TEXT COLLATE "C" NOT NULL,
    original_path TEXT COLLATE "C" NOT NULL,
    captured TEXT COLLATE "C" NOT NULL DEFAULT '',
    rating BIGINT NOT NULL DEFAULT 0 CHECK(rating BETWEEN 0 AND 5),
    flag BIGINT NOT NULL DEFAULT 0 CHECK(flag BETWEEN -1 AND 1),
    label TEXT COLLATE "C" NOT NULL DEFAULT '',
    format TEXT COLLATE "C" NOT NULL DEFAULT '',
    copy_name TEXT COLLATE "C" NOT NULL DEFAULT '',
    master_id BIGINT,
    orientation TEXT COLLATE "C",
    lightroom_develop TEXT COLLATE "C",
    recipe TEXT COLLATE "C",
    export_options TEXT COLLATE "C",
    identity TEXT COLLATE "C",
    edited_at TEXT COLLATE "C"
);

CREATE INDEX IF NOT EXISTS photos_folder ON photos(folder);

CREATE INDEX IF NOT EXISTS photos_captured ON photos(captured);

CREATE INDEX IF NOT EXISTS photos_master ON photos(master_id);

CREATE TABLE IF NOT EXISTS collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT COLLATE "C" NOT NULL,
    parent BIGINT,
    kind TEXT COLLATE "C" NOT NULL
);

CREATE TABLE IF NOT EXISTS collection_photos (
    collection BIGINT NOT NULL REFERENCES collections(id),
    photo BIGINT NOT NULL REFERENCES photos(id),
    position TEXT COLLATE "C",
    PRIMARY KEY(collection,photo)
);

CREATE TABLE IF NOT EXISTS keywords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT COLLATE "C" NOT NULL,
    parent BIGINT
);

CREATE TABLE IF NOT EXISTS photo_keywords (
    photo BIGINT NOT NULL REFERENCES photos(id),
    keyword BIGINT NOT NULL REFERENCES keywords(id),
    PRIMARY KEY(photo,keyword)
);

CREATE TABLE IF NOT EXISTS folder_mappings (
    folder BIGINT PRIMARY KEY REFERENCES folders(id),
    path TEXT COLLATE "C" NOT NULL
);

-- Added after version 1 shipped.

-- Lightroom's develop history per photo: one full settings snapshot per step.
CREATE TABLE IF NOT EXISTS lightroom_history (
    photo BIGINT NOT NULL,
    position BIGINT NOT NULL,
    name TEXT COLLATE "C" NOT NULL DEFAULT '',
    created DOUBLE PRECISION,
    -- Lightroom stores a step as text or as length-prefixed zlib bytes.
    text BYTEA NOT NULL,
    PRIMARY KEY(photo, position)
);

-- Revision 1 made `text` TEXT, which cannot hold those bytes.
DO $$
BEGIN
    IF (SELECT data_type FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'lightroom_history'
          AND column_name = 'text') = 'text' THEN
        ALTER TABLE lightroom_history
            ALTER COLUMN text TYPE BYTEA USING convert_to(text, 'UTF8');
    END IF;
END $$;

-- Spots and masks of a photo's edit (experimental), as `LocalEdits` JSON: kept out
-- of the recipe column so releases before them still read every edit.
CREATE TABLE IF NOT EXISTS local_edits (
    photo BIGINT PRIMARY KEY,
    data TEXT COLLATE "C" NOT NULL
);

-- A photo's Develop History (see `develop_history`), saved with its edit.
CREATE TABLE IF NOT EXISTS develop_history (
    photo BIGINT PRIMARY KEY REFERENCES photos(id) ON DELETE CASCADE,
    data BYTEA NOT NULL
);

-- Develop Snapshots (see `snapshots`): a RAWmakase recipe as JSON, or Lightroom's
-- settings text for snapshots imported from Lightroom.
CREATE TABLE IF NOT EXISTS develop_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photo BIGINT NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
    name TEXT COLLATE "C" NOT NULL,
    recipe TEXT COLLATE "C",
    lightroom BYTEA
);
CREATE INDEX IF NOT EXISTS develop_snapshots_photo ON develop_snapshots(photo);

-- Compressed bitmaps referenced by hash from saved recipes (see `storage::bitmaps`).
CREATE TABLE IF NOT EXISTS bitmaps (
    hash TEXT COLLATE "C" PRIMARY KEY,
    data BYTEA NOT NULL
);

-- Camera settings and size of a photo, from the Lightroom catalog it came from
-- or read from its file; a row of NULLs records a file that had none.
CREATE TABLE IF NOT EXISTS photo_info (
    photo BIGINT PRIMARY KEY,
    camera TEXT COLLATE "C",
    lens TEXT COLLATE "C",
    focal DOUBLE PRECISION,
    aperture DOUBLE PRECISION,
    exposure DOUBLE PRECISION,
    iso DOUBLE PRECISION,
    width BIGINT,
    height BIGINT
);

-- Facts about the catalog itself, by name.
CREATE TABLE IF NOT EXISTS meta (
    key TEXT COLLATE "C" PRIMARY KEY,
    value TEXT COLLATE "C" NOT NULL
);

-- Descriptive metadata set in RAWmakase or imported, per photo: a virtual copy
-- keeps its own rows, never its master's. A field with no row is the file's
-- own. Rows go with their photo, also when a release that does not know these
-- tables removes it, so a later photo reusing the id inherits nothing.

-- Whether a field (title, caption, creator, copyright) is set or cleared.
CREATE TABLE IF NOT EXISTS photo_fields (
    photo BIGINT NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
    field TEXT COLLATE "C" NOT NULL,
    state TEXT COLLATE "C" NOT NULL CHECK(state IN ('set', 'cleared')),
    PRIMARY KEY(photo, field)
);

-- The languages of a set title, caption or copyright: "x-default" and any
-- others imported, in their order (the first is the default when there is
-- no "x-default").
CREATE TABLE IF NOT EXISTS photo_text (
    photo BIGINT NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
    field TEXT COLLATE "C" NOT NULL,
    lang TEXT COLLATE "C" NOT NULL,
    position BIGINT NOT NULL,
    value TEXT COLLATE "C" NOT NULL,
    PRIMARY KEY(photo, field, lang)
);

-- A set creator's names, in order.
CREATE TABLE IF NOT EXISTS photo_creators (
    photo BIGINT NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
    position BIGINT NOT NULL,
    name TEXT COLLATE "C" NOT NULL,
    PRIMARY KEY(photo, position)
);

-- A capture time from elsewhere than the file (a Lightroom catalog, a
-- sidecar): local "YYYY-MM-DDTHH:MM:SS", the subsecond digits as read, and
-- the offset ("+02:00") when known. `photos.captured` is the sort key.
CREATE TABLE IF NOT EXISTS photo_capture (
    photo BIGINT PRIMARY KEY REFERENCES photos(id) ON DELETE CASCADE,
    captured TEXT COLLATE "C" NOT NULL,
    subsec TEXT COLLATE "C",
    "offset" TEXT COLLATE "C"
);

-- A location from elsewhere than the file, or the file's cleared.
CREATE TABLE IF NOT EXISTS photo_location (
    photo BIGINT PRIMARY KEY REFERENCES photos(id) ON DELETE CASCADE,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    alt DOUBLE PRECISION,
    cleared BIGINT NOT NULL DEFAULT 0
);

-- Keywords are looked up by parent and name; not unique, as Lightroom
-- catalogs can hold duplicates.
CREATE INDEX IF NOT EXISTS keywords_parent_name ON keywords(parent, name);

-- Lightroom's export options of a keyword, where one is off: Include on
-- Export (`include`) and Export Containing Keywords (`parents`). A keyword
-- with no row exports with its parents.
CREATE TABLE IF NOT EXISTS keyword_export (
    keyword BIGINT PRIMARY KEY REFERENCES keywords(id) ON DELETE CASCADE,
    include BIGINT NOT NULL,
    parents BIGINT NOT NULL
);
